name: Main

on:
  push:
    branches:
      - main

env:
  ACTION_NAME: extract-release-commit

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0

  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Test 1
        id: test1
        uses: ./
        with:
          commit_message: "chore(main): release 0.1.4"

      - run: |
          [[ "${{ steps.test1.outputs.version }}" == "0.1.4" ]]

      - name: Test 2
        id: test2
        uses: ./
        with:
          commit_message: "chore(main): other chore 1.2.9"

      - run: |
          [[ "${{ steps.test2.outputs.version }}" == "" ]]

  release-pull-request:
    runs-on: ubuntu-latest
    needs: [pre-commit, test]
    steps:
      - uses: google-github-actions/release-please-action@v3.4.1
        id: release
        with:
          release-type: simple
          command: release-pr
          package-name: ${{ env.ACTION_NAME }}
          bump-minor-pre-major: true
